# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


2) Создать нулевой вектор размера 10

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((1,7),7)

array([[7, 7, 7, 7, 7, 7, 7]])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
arr = np.linspace(10, 100, 46, dtype=int)
arr

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
arr = np.random.randn(10)

print(arr)

arr[::-1]

[ 1.68159423 -0.60374934 -0.35401038 -0.68864363  0.33238911  0.73128163
  0.54373104  0.98805738  1.36157209 -0.5672542 ]


array([-0.5672542 ,  1.36157209,  0.98805738,  0.54373104,  0.73128163,
        0.33238911, -0.68864363, -0.35401038, -0.60374934,  1.68159423])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
arr = np.eye(4, k=1)
arr

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
arr = np.full((4,4),7)
np.fill_diagonal(arr, [1,2,3,4])
arr

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
arr = np.arange(5)
np.repeat(arr,5).reshape(5,5).transpose()



array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
arr = np.random.randint(0, 10, (10, 10))
avg = arr.mean()
res = arr - avg

print(arr)
print(res)


[[7 9 8 3 7 3 2 7 6 2]
 [8 9 8 2 5 9 9 7 9 1]
 [6 6 3 9 5 4 5 0 1 0]
 [5 4 4 5 3 4 7 6 7 5]
 [6 7 7 1 3 9 2 4 7 5]
 [2 8 5 7 9 7 4 7 5 4]
 [0 7 3 7 1 8 9 4 9 8]
 [5 2 1 0 3 8 4 5 7 7]
 [8 3 6 6 9 3 9 3 6 1]
 [4 4 4 2 5 0 7 4 8 9]]
[[ 1.82  3.82  2.82 -2.18  1.82 -2.18 -3.18  1.82  0.82 -3.18]
 [ 2.82  3.82  2.82 -3.18 -0.18  3.82  3.82  1.82  3.82 -4.18]
 [ 0.82  0.82 -2.18  3.82 -0.18 -1.18 -0.18 -5.18 -4.18 -5.18]
 [-0.18 -1.18 -1.18 -0.18 -2.18 -1.18  1.82  0.82  1.82 -0.18]
 [ 0.82  1.82  1.82 -4.18 -2.18  3.82 -3.18 -1.18  1.82 -0.18]
 [-3.18  2.82 -0.18  1.82  3.82  1.82 -1.18  1.82 -0.18 -1.18]
 [-5.18  1.82 -2.18  1.82 -4.18  2.82  3.82 -1.18  3.82  2.82]
 [-0.18 -3.18 -4.18 -5.18 -2.18  2.82 -1.18 -0.18  1.82  1.82]
 [ 2.82 -2.18  0.82  0.82  3.82 -2.18  3.82 -2.18  0.82 -4.18]
 [-1.18 -1.18 -1.18 -3.18 -0.18 -5.18  1.82 -1.18  2.82  3.82]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
arr = np.random.randint(0, 10, (10, 10))
med = np.median(arr)
res = arr - med

print(arr)
print(res)


[[4 2 3 4 1 8 8 9 6 5]
 [8 2 5 5 4 0 7 7 4 2]
 [1 0 3 6 1 8 0 9 8 7]
 [8 5 0 1 4 2 7 8 7 6]
 [1 0 7 2 4 2 4 6 8 5]
 [3 0 9 8 4 3 2 9 4 0]
 [7 3 7 3 5 8 3 4 4 8]
 [1 6 2 0 5 7 3 4 8 9]
 [4 2 6 0 6 6 7 6 6 6]
 [8 7 7 4 6 4 5 5 3 5]]
[[-1. -3. -2. -1. -4.  3.  3.  4.  1.  0.]
 [ 3. -3.  0.  0. -1. -5.  2.  2. -1. -3.]
 [-4. -5. -2.  1. -4.  3. -5.  4.  3.  2.]
 [ 3.  0. -5. -4. -1. -3.  2.  3.  2.  1.]
 [-4. -5.  2. -3. -1. -3. -1.  1.  3.  0.]
 [-2. -5.  4.  3. -1. -2. -3.  4. -1. -5.]
 [ 2. -2.  2. -2.  0.  3. -2. -1. -1.  3.]
 [-4.  1. -3. -5.  0.  2. -2. -1.  3.  4.]
 [-1. -3.  1. -5.  1.  1.  2.  1.  1.  1.]
 [ 3.  2.  2. -1.  1. -1.  0.  0. -2.  0.]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
arr = np.random.randint(0, 10, (5, 5))
max = arr.max(axis=1, keepdims=True)
min = arr.min(axis=1, keepdims=True)
res = np.hstack((arr, max, min))

print(arr)
print(res)


[[4 5 3 9 0]
 [9 6 7 2 2]
 [3 4 0 6 7]
 [8 9 5 5 7]
 [4 0 0 0 6]]
[[4 5 3 9 0 9 0]
 [9 6 7 2 2 9 2]
 [3 4 0 6 7 7 0]
 [8 9 5 5 7 9 5]
 [4 0 0 0 6 6 0]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
arr = np.arange(1, 52)

nechet = arr[arr % 2 != 0]
chet = arr[arr % 2 == 0]

nechet_arr = nechet[:25].reshape(5, 5)
chet_arr = chet[:25].reshape(5, 5)

res = np.dot(nechet_arr, chet_arr)
if np.linalg.det(res) != 0:
    inverse_matrix = np.linalg.inv(res)
    print("Обратная матрица произведения:\n", inverse_matrix)
else:
    print("Обратная матрица не существует, так как произведение является вырожденной матрицей.")




Обратная матрица не существует, так как произведение является вырожденной матрицей.


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
arr = np.zeros((8, 8))

arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])